intent:
    password:
        de:
            unknown_entry: ["Ich habe keine Zugangsdaten für {} gefunden."]
            typed_pw: "Passwort für {} getippt"
            db_not_found: "Die Passwortdatenbank wurde nicht gefunden."
            key_not_found: "Der Schlüssel für die Datenbank wurde nicht gefunden."
            could_not_access_keystore: "Konnte Passwortdatenbank nicht öffnen."
            no_voice_match: "Du darfst leider nicht auf die Passwortdatenbank zugreifen."
        en:
            unknown_entity: ["I could not find any credentials for {}."]
            typed_pw: "Typed password for {}"
            db_not_found: "The key database was not found."
            key_not_found: "The secret key to access the database was not found."
            could_not_access_keystore: "Could not open keystore"
            no_voice_match: "You are not allowed to access the keystore"
        db_file: ./db.kdbx
        key_file: ./secret.keyx
        